docs/_quarto.yml
docs/styles.css
example/bar/seaborn/example_sns_bar_plot.py
example/box/matplotlib/example_mpl_box.py
example/box/seaborn/example_sns_box.py
maidr/core/plot/boxplot.py
maidr/patch/boxplot.py
tests/core/plot/test_boxplot.py

feat(boxplot): support horizontal orientation

---

maidr/core/plot/boxplot.py
maidr/patch/boxplot.py

fix(boxplot): support seaborn axes flip

---

maidr/__init__.py
maidr/core/figure_manager.py
maidr/core/maidr.py
maidr/core/plot/boxplot.py
maidr/core/plot/grouped_barplot.py
maidr/core/plot/histogram.py
maidr/core/plot/scatterplot.py
maidr/maidr.py
maidr/patch/clear.py

fix: seaborn multi plots in same session

---

pyproject.toml

testing if this fixes docs release failure.

ci: upgrade quartodoc version

---

.github/workflows/docs.yml

render and publish docs, only for xability/py_maidr repo

ci: add repo name condidtion to docs workflow

---

.commitlintrc.js

ci(commitlint): disable commitlint line length and total length checking

---

example/streamlit/example_streamlit_app.py

This PR includes an example streamlit web app to demonstrate interactivity capabilities with maidr. 
closes #84 
Added a new file `example_streamlit_app.py` under streamlit folder in example directory.

docs(example): add `streamlit` dashboard demo with `maidr`

---

.github/workflows/docs.yml

This PR fixes the Quarto publish workflow by ensuring that the Quarto action uses the project’s Python virtual environment. It sets the QUARTO_PYTHON environment variable so that Quarto can properly execute code cells and render the documentation without encountering missing module errors.

fix: set QUARTO_PYTHON environment variable in docs workflow

---

docs/examples.qmd
docs/index.qmd

The main changes include fixing the scroll behavior to ensure a smoother user experience when navigating through the documentation pages. This update is aimed at improving accessibility and readability for users.
Adjusted the figsize for each plot, to avoid the scroll bars.

docs: adjust figure sizes and formatting in examples.qmd

---

maidr/util/environment.py

This fix solves the problem of maidr.show not showing the interactive plot in google colab environment. This happened because is_notebook function returned False for Google Colab environment. 
Added a check in is_notebook where we check if google.colab exists in str(get_ipython())

fix: address an issue where is_notebook returns false in Google Colab

---

maidr/core/maidr.py

This PR is related to the change that we did where we added a maidr attribute to SVG element in maidr js repository. This accomodates that change in PyMaidr so that we can directly add maidr attribute to SVG instead of adding a maidr object in the script tags.
NA

feat: add 'maidr-data' attribute to SVG elements

---

example/scatter/matplotlib/example_mpl_scatter.py
example/scatter/seaborn/example_sns_scatter.py
maidr/core/plot/scatterplot.py

This PR adds support for scatter plot by making use of Maidr's TypeScript Engine.

feat: support scatter plot using maidr-ts

---

maidr/core/plot/scatterplot.py

This PR fixes highlight issue with ScatterPlot when using maidr ts engine.

fix: update selector logic in ScatterPlot for correct element targeting

---

maidr/core/plot/grouped_barplot.py

This PR adds support for highlight in dodged and stacked bar plots when using maidr-ts engine.

feat: support highlight in dodged and stacked bar plot using maidr-ts

---

example/dodged/seaborn/example_sns_dodged.py
maidr/patch/barplot.py

fix: ensure dodge plot type is correctly set in seaborn

---

example/stacked/matplotlib/example_mpl_stacked.py
maidr/core/plot/grouped_barplot.py

This fixes #173 where the fill label was not properly being displayed.

fix(stacked barplot): address an issue where fill label is not working

---

maidr/core/maidr.py

fix: change maidrjs version

---

.github/workflows/release.yml

chore: revert semantic release plugin change

---

maidr/core/plot/candlestick.py
maidr/core/plot/maidr_plot.py
maidr/core/plot/mplfinance_barplot.py
maidr/core/plot/mplfinance_lineplot.py

Refactored layer switch logic in upstream. Added layer id for switch check. So this caused layer switching to break. This fix is to add layer id for every layer

fix: add layer id for layers

---

maidr/api.py

https://github.com/xability/py-maidr/issues/221
Added check for list to api.render similar to the check in .show and .save_html
- [] I have commented my code, particularly in hard-to-understand areas.

fix(candlestick): address rendering error

---

.github/workflows/ci.yml
uv.lock

sync uv.lock file and add uv lockfile check in ci.yml

ci: sync lock

---

example/flask/test_flask_app.py
maidr/core/maidr.py
maidr/util/environment.py
pyproject.toml
uv.lock

Added Environment.is_flask which tries to import flask and checks if there is a current app context. If both work, return True, else False.
Updated check for shiny or notebook to check is_flask as well and render outputs an iframe.

feat: detect if running in a flask app and render in an iframe
