xability/py-maidr

- .github/workflows/commit-message-lint.yml
This pull request adds a conventional commits linter to the GitHub workflow. The linter ensures that all commits follow the conventional commits format. This helps maintain consistency and readability in the Rcommit history. Fixes #5
> ci: add conventional commits linter to gh workflow

- .gitignore
- docs/_quarto.yml
- docs/styles.css
- maidr/core/figure_manager.py
- maidr/core/maidr.py
`_quarto.yml` includes the base structure of the static website with a navbar and the main site.  The navbar includes 'Overview', 'Get Started', and 'API Referece' sections, which are structured in `_index.qmd`, `_get_started.qmd`, and the quartodoc section of `_quarto.yml` respectively. Currently, the 'Overview' and 'Get Started' sections are left empty, which will be generated in the upcoming releases. The 'API Reference' section will include the docstring in a neat format generated by `quartodoc`.
Resolves: #17
> docs: add quarto and quartodoc for static website

- .github/workflows/docs.yml
`docs.yml` automates the publishing of py-maidr documentation to GitHub Pages. This builds the
static sources using `quarto` for the website and `quartodoc` for the API Reference.
The rendering and publishing are accomplished using Quarto's github actions, which can be found
at https://github.com/quarto-dev/quarto-actions.
Resolves: #43
> ci: add workflow for publishing docs

- .github/workflows/docs.yml
> ci: fixate python version in docs action

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Added bug report and feature request templates to improve the issue creation process. These templates provide a standardized structure for reporting bugs and requesting new features, making it easier for contributors to provide clear and concise information. This will help streamline the issue triage and resolution process.
The bug report template includes sections for describing the bug, steps to reproduce, actual and expected behavior, screenshots, and additional information. The feature request template includes sections for describing the requested feature, motivation, proposed solution, and additional context.
This pull request addresses issue #80.
> chore: add new issue and pull request templates

- .flake8
- example/py-shiny/example_pyshiny_reactive_scatter.py
- maidr/__init__.py
- maidr/api.py
- maidr/core/maidr.py
- maidr/patch/histogram.py
- maidr/widget/shiny.py
- poetry.lock
- pyproject.toml
This PR adds support for maidr on py-shiny through a custom renderer called `render_maidr`. This decorator internally calls the newly created `maidr.render` function to transform a plot of the matplotlib type to a maidr object and envelops it as an iframe srcdoc for display on a py-shiny web dashboard.
Closes [#65]
> feat(maidr.show): support py-shiny renderer

- example/bar/example_bar_plot.ipynb
- maidr/core/plot/heatmap.py
- maidr/patch/heatmap.py
This PR picks up the seaborn heatmap's fmt argument and applies it to the values displayed in maidr. This is done so by passing the argument fmt to the patched heatmap plot. 
closes #77 
1. Parsed the fmt argument from kwargs in the heatmap patch.
2. Passed the fmt argument in FigureManager's create_maidr function.
3. Stored the value of fmt, which helps to format the values to display
> feat: pick up seaborn heatmap fmt towards maidr

- pyproject.toml
This pull request updates the `exclude_commit_patterns` in the `pyproject.toml` file. The previous commits that don't match the conventional commits prefixes and internal changes that do not necessarily affect end-user interactions, such as `chore`, `ci`, and `style`, are excluded from our CHANGELOG and GitHub release note moving forward. This is not a direct fix, but after this change, it ensures that only relevant commits are included in the release changelog as a fair stopgap solution.
Closes #99
> ci(semantic-release): exclude non-conventional commits from `CHANGELOG`

- README.md
- maidr/core/maidr.py
- maidr/util/environment.py
This pull request fixes the handling of API keys for LLMs in the code. It adds a JavaScript script to handle the API keys for LLMs and initializes the LLM secrets in the MAIDR instance. The script injects the LLM API keys into the MAIDR instance and sets the appropriate settings based on the presence of the Gemini and OpenAI API keys. This ensures that the LLM functionality works correctly with the updated API key handling.
closes #76 
1. Added a new method called `initialize_llm_secrets()` in environment.py which fetches the keys from the environment variable.
2. Injected the script when the maidr iframe loads initially.
> feat: fetch LLM API keys from user env variables

- maidr/core/maidr.py
This PR includes changes for removing overflow on iframes and resizing them according to content of the plot.
This PR introduces JavaScript based changes to the generated iframe. We strictly remove overflow and scrolling for the plot that is maidr active and attach event listeners to find out the onFocus element. The major overflow happens when braille is activated. To address that, we have attached an onfocus event listener to the `braille-div` container and decide if we need to expand size of the iframe to accommodate for the additional space at the top.
This PR includes all changes made by @dakshpokar in his recent draft PR along with the Shiny specific changes I have made.
> fix: address dynamic resizing of iframes on ipython

- maidr/core/maidr.py
This PR includes changes for removing overflow on iframes and resizing them according to content of the plot.
This PR enhances iframe resizing behavior to dynamically adjust height and width based on content size and user interaction. Specifically, the height is recalculated with additional space (100px) when the braille-input field is focused, and 50px otherwise. This ensures the iframe is not clipped during braille mode. The script also adds event listeners for focusin, focusout, and resize events to trigger appropriate resizing as needed, which were added by @krishnanand5.
> fix: address iframe resizing issue in jupyter notebooks

- poetry.lock
- pyproject.toml
This PR aims to address a CVE-2024-53899 vulnerability detected on py_maidr.
The Github autoscan of the py_maidr repository identified a CVE-2024-53899 vulnerability with the repository. Upon further investigation, it was revealed that the issue is with **virtualenv** before **20.26.6**  as it allows command injection through the activation scripts for a virtual environment. 
https://github.com/advisories/GHSA-rqc4-2hc7-8c8v - Github Advisory's account of CVE-2024-53899.
Virtualenv has been bumped up to 20.28.1.
> ci: update virtualenv to higher than 20.26.6

- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
This PR updates poetry.lock to aid in virtualenv version updation.
> ci: update poetry.lock to adhere to v2.0.0

- example/dodged/matplotlib/example_mpl_dodged.py
- maidr/patch/barplot.py
This change adds a numeric check for the x positions in bar plots, allowing automatic detection of dodged (grouped) bar plots when x is numeric. By inspecting whether x is a NumPy array of a numeric dtype (or a numeric Python list/tuple), the code now updates the plot type to PlotType.DODGED. This ensures better handling of grouped bar plots, making it more convenient for users to visualize their data.
closes #135
> feat: add dodged bar plot support along with an matplotlib example

- docs/_environment
- maidr/core/maidr.py
- maidr/util/environment.py
This pull request introduces an iframe-free solution. However, it cannot be fully implemented yet because keybindings in Jupyter Notebook, Google Colab, and VSCode's IPython Notebook still need to be fixed. Once we resolve the keybindings issue, we can remove the conditional check that currently renders maidr inside an iframe, and the solution will function seamlessly. For now, plots on these platforms will continue to be rendered within an iframe.
NOTE: It's very crucial to first merge the maidr.js PR before merging this PR
https://github.com/xability/maidr/pull/637
addesses #108 
1. Added maidr_id attribute to handle unique identifiers for Maidr instances.
2. Updated _inject_plot method to include maidr_id in the SVG.
3. Added a new method is_vscode_notebook to check if the environment …
> fix: remove iframe in support of iframeless rendering

- maidr/core/maidr.py
This PR fixes the issue where only the first plot had the aria-label maidr instruction on how to activate.
> fix: update initialization method to use window.init on DOMContentLoaded

- maidr/core/maidr.py
Recent py-maidr had an issue with Shiny. If you change colors or distribnution types of histograms in this example file, nothing is displayed. Only the initial plot is shown. This was fix in this PR by removing the DOMContentLoaded event wrapper around the window.init() call.
> fix: address pyshiny initialization in maidr

- maidr/core/plot/lineplot.py
This issue fixes the empty lines in data array in the maidr json object in case of Seaborn.
> fix: prevent appending empty line data in MultiLinePlot

- example/histogram/matplotlib/example_mpl_hist.py
- example/histogram/seaborn/example_sns_hist.py
- maidr/core/enum/maidr_key.py
This PR adds support for histogram plots in py-maidr using maidr-ts engine. Please note that adding support for histogram using maidr-ts eliminates backwards support using py-maidr with maidr-js engine.
> feat: support histogram plot using maidr-ts

- maidr/core/plot/lineplot.py
> fix: address type hints for _extract_line_data method in MultiLinePlot

- .github/workflows/ci.yml
- maidr/core/plot/lineplot.py
Currently, when running the PyMaidr CI it fails with this error - _"The virtual environment found in /home/runner/work/py-maidr/py-maidr/.venv seems to be broken."_ This happened because wrong .venv is being restored when restoring from cache. To fix this we can use setup-python’s built‑in cache stores which is immune to interpreter mismatches and is officially recommended by GitHub.
> fix: replace caching for Poetry dependencies in CI workflow

- example/multiline/matplotlib/example_mpl_multiline.py
- maidr/core/plot/lineplot.py
This PR fixes the issue where a redundant _child0 is added as a fill parameter to the line plots when using maidr-ts. To fix this a check if added to ensure this is not added if the label is not provided.
> fix: remove redundant _child0 label as a fill parameter for line plot

- example/box/matplotlib/example_mpl_box.py
- maidr/core/plot/boxplot.py
This PR fixes the boxplot highlight issue where outliers (upper and lower) were highlight together instead of being highlighted separately. This pull request introduces a more precise method for selecting lower and upper outlier elements within our SVG visualizations. Previously, both lower and upper outliers shared a common, less specific selector. This change differentiates them based on their order and visibility within a shared outlier group, leveraging modern CSS selector capabilities.
The primary motivation is to enable more accurate and distinct identification and styling of lower versus upper outliers, which was not directly possible with the previous undifferentiated selector. This change assumes that all outlier points are grouped under a common SVG group element (identified by …
> fix(boxplot): enhance outlier handling by separting outliers

- maidr/api.py
- maidr/core/maidr.py
Closes #190 
Address an issue where iframe is used for maidr.show rendering when saved in IPython notebooks
Core Changes (maidr/core/maidr.py)
1. Added use_iframe parameter to _inject_plot() method (default: True)
2. Modified _create_html_tag() and _create_html_doc() to accept use_iframe parameter
3. Updated save_html() to use use_iframe=False (always direct HTML)
4. Updated show() and render() to use use_iframe=True (maintains iframe for display)
> fix: address iframe tag issue in `save_html()`

- maidr/core/plot/lineplot.py
- maidr/patch/lineplot.py
Issue:
The multiline plot functionality had a data format mismatch between the backend and frontend:
Backend Output: Multiple MAIDR layers (one per line) with individual data arrays
Frontend Expectation: Single layer with multiple data arrays (one per line)
The patch was creating separate MAIDR plots for each plt.plot() call, resulting in:
1. Multiple layers in the output JSON
2. Each layer containing all lines' data and frontend unable to process the nested structure correctly
Solution
1. Modified the lineplot patch to create one MAIDR plot per axes instead of per line call:
2. Added axes-level tracking: Used _maidr_plot_created flag to prevent multiple MAIDR plots
3. Updated data extraction: Modified MultiLinePlot to extract all lines as separate arrays within a single layer
4. Fixed …
> fix: address multiline plot highlight

- maidr/core/enum/smooth_keywords.py
- maidr/patch/regplot.py
- maidr/util/regression_line_utils.py
Problem: When using sns.regplot with multiple smooth lines (e.g., linear regression + LOWESS), only one smooth line was being detected and registered as a MAIDR layer.
Solution:
Enhanced find_smooth_lines_by_label() utility function to detect smooth lines with generic _child labels (created by seaborn's regplot)
Modified regplot patch to process all detected smooth lines and register each as a separate MAIDR layer
Changes:
maidr/patch/regplot.py: Refactored to use utility function and handle multiple smooth lines
> fix: address reg plot multi-line detection

- .github/workflows/release.yml
- pyproject.toml
[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
This action already publishes to github releases, and the last step is redundant. So removing that part.
> ci: remove redundant github releases
